version: '3.4'

services:

  pg:
    image: postgres:14.8
    container_name: postgres
    command: postgres -c 'max_connections=400'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"